export type BookTheme = 'editorial' | 'polaroid' | 'minimal'
export type BookSize = 'square' | 'a5'
export type ChapterLayout = 'full' | 'duo' | 'trio' | 'text'
/** duo: row(나란히) | stack(위아래), trio: left(히어로 왼쪽) | top(히어로 위) — 없으면 row / left */
export type ChapterVariant = 'row' | 'stack' | 'left' | 'top'

interface PageBase {
  id: string
}

export interface CoverPage extends PageBase {
  kind: 'cover'
  title: string
  subtitle: string
  photoId?: string
}
export interface IntroPage extends PageBase {
  kind: 'intro'
  body: string
  quote: string
}
export interface ChapterPage extends PageBase {
  kind: 'chapter'
  sceneId?: string
  /** 같은 챕터의 이어지는 사진 쪽이면 true (제목·번호를 줄여서 표시) */
  continued?: boolean
  heading: string
  body: string
  layout: ChapterLayout
  variant?: ChapterVariant
  photoIds: string[]
  captions: Record<string, string>
}
export interface QuotePage extends PageBase {
  kind: 'quote'
  text: string
}
export interface ClosingPage extends PageBase {
  kind: 'closing'
  body: string
  tags: string[]
}
export interface BackPage extends PageBase {
  kind: 'back'
}

export type BookPage = CoverPage | IntroPage | ChapterPage | QuotePage | ClosingPage | BackPage
export type BookPageKind = BookPage['kind']

export interface Storybook {
  id: string
  projectId: string
  theme: BookTheme
  size: BookSize
  pages: BookPage[]
  /** 인용 페이지에 쓰는 배경(그라데이션 또는 이미지 URL) */
  background?: string
  backgroundCredit?: string
  autoGeneratedAt: string
  updatedAt: string
}
